apiVersion: v1
kind: Secret
metadata:
  name: theshop-api-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: theshop-api
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
  default-connection: {{ printf "Host=%s;Port=%d;Database=%s;Username=%s;Password=%s" (ternary "postgres-external" .Values.postgresql.host .Values.externalServices.enabled) (.Values.postgresql.port | int) .Values.postgresql.database .Values.postgresql.username .Values.postgresql.password | quote }}
  openai-api-key: {{ .Values.chatbot.openAiApiKey | quote }}

